# Generated by Django 3.2.5 on 2021-08-07 07:28

import app2.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('author_lang', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(choices=[('001', 'pavi'), ('002', 'thooriga'), ('jingly', '003'), ('pavithra', 'jingly'), ('dinesh', 'dinu'), ('sofi', 'gopi')], max_length=200)),
                ('author_name', models.CharField(choices=[('001', 'pavi'), ('002', 'thooriga'), ('jingly', '003'), ('pavithra', 'jingly'), ('dinesh', 'dinu'), ('sofi', 'gopi')], max_length=200)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('place', models.CharField(default='delhi', max_length=200)),
                ('review', models.CharField(blank=True, max_length=100, null=True)),
                ('present', models.BooleanField(null=True)),
                ('student_date', models.DateTimeField(default=datetime.datetime(2021, 8, 7, 7, 28, 43, 547604, tzinfo=utc))),
                ('phnum', models.BigIntegerField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Student_updated', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(default='pavi@gmail.com', max_length=254)),
                ('address', models.CharField(max_length=250, validators=[app2.models.Validate_chennai])),
                ('profile_pic', models.ImageField(null=True, upload_to='images/%y/%m/%d')),
                ('resume', models.FileField(null=True, upload_to='userfile/%y/%m/%d')),
                ('rating', models.TextField(blank=True, help_text='pls fill rating starting from 5', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_a', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.BigIntegerField()),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app2.employee')),
            ],
        ),
        migrations.CreateModel(
            name='novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel_name', models.CharField(max_length=200)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.author')),
            ],
        ),
        migrations.CreateModel(
            name='club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=200)),
                ('members', models.ManyToManyField(to='app2.member')),
            ],
        ),
    ]
